spring.application.name=bus-ticket-frontend-test
backend.base-url=http://localhost:8080
backend.connect-timeout-ms=1000
backend.read-timeout-ms=2000
spring.thymeleaf.cache=false
spring.main.banner-mode=off
logging.level.root=WARN
